name: "Create default user"
stages:
  initramfs:
    - name: "Create hcos user with default password"
      users:
        # TODO: do not set password for the root user. This is temporary for easy troubleshooting.
        root:
          passwd: hcos
