name: Build image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Earthly
        uses: earthly/actions-setup@v1
      - name: Earthly version
        run: earthly --version
